### ISSUE TITLE
Refactor Kotlin code for readability

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-alliance/stay-awake-app#13]
Currently the codebase uses a lot of Kotlin scoping functions (let, apply, with, etc) which make the code difficult to read. Refactor the codebase so that it is easy to read, and debug.

**Comment by nazmulidris** [comment]
@fkubicek Thanks for the PR and responding to the open issue! 🙏.

I'm planning to refactor the code so that it's more readable. If you want I can show you what I'm doing before I do it, since we never went thru code review in the previous PRs if that would would be useful to you. PLMK.

On an unrelated note, I just wrote an interesting Kotlin annotation processing repo if you are interested meta-programming and code generation: https://github.com/nazmulidris/annotation-processing/tree/main/kotlin-android-project

**Comment by fkubicek** [comment]
I've sent you an email, sou you should have my address now :) Thanks for inviting me to this repo, I just realised that I can now merge my own PR. 😃 Should I just do it? Or should I leave merging things into the main branch on you? I have no clue what would be appropriate here.

**Comment by nazmulidris** [comment]
- This commit fixes this issue: d9bae17d4115be7f2ef8d5afabd54ff4dd1cfc6e
- All changes to this point are pushed to the Play Store as release 2.6: https://github.com/r3bl-org/stay-awake-app/releases/tag/2.6
