### ISSUE TITLE
Samsung Note20 Ultra (not staying awake)

### ISSUE THREAD

**Issue by alupnyas** [r3bl-alliance/stay-awake-app#14]
Hello,

Just upgraded from Samsung Note10 to Note20 Ultra and my phone does not stay awake with this App. Last time this app worked was on my Note8. I was informed sometime back developers were planning to make sure Note20 would work.

Is there some tweak I need to donto make this work?

Please advise,
~Jp

**Comment by nazmulidris** [comment]
Sorry to hear that you're having issues w/ the app. We don't actually test the app on Samsung phones (only Pixel devices). So I'm not sure why it isn't working. Unfortunately, we don't plan to support Samsung phones. There might be other apps that work better on your device than this one.
