### ISSUE TITLE
Improve awake UI

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-alliance/stay-awake-app#8]
1. Add support for dark and light mode

2. Improve the design and layout of the main activity (better button, better spacing, better layout)

3. Add logo at the bottom of the page

**Comment by NadiaIdris** [comment]
Low fidelity mock of new main activity
https://photos.app.goo.gl/agX8rnMyV1tUUgkS6

**Comment by nazmulidris** [comment]
Let's add a R3BL logo on the bottom of the app and cleanup the links for the GitHub repo and issue tracker.
